version: "3.8"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: coach_demon
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  coach_demon:
    build:
      context: .
      target: runtime
    depends_on:
      - mongo
    ports:
      - "12345:12345"
    volumes:
      - ./config.yaml:/config.yaml:ro

  dozzle:
    image: amir20/dozzle
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  tests:
    build:
      context: .
      target: tests
    depends_on:
      - mongo
      - coach_demon
    working_dir: /src
    volumes:
      - ./tests:/src/tests
      - ./tests/reports:/reports
      - ./config.yaml:/config.yaml:ro
volumes:
  mongo_data:
